// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zzcverwzrpfhcvnhvihb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y3Zlcnd6cnBmaGN2bmh2aWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjQ2ODQsImV4cCI6MjA3Nzk0MDY4NH0.rTBAKOa0FRn074IGDalfe7WD9_yXNUVFrF08Z8SmkPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);